packages:
  - playgrounds/*
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^6.2.0
  '@antfu/ni': ^27.0.1
  '@antfu/utils': ^9.3.0
  '@eslint-react/eslint-plugin': ^2.3.1
  '@shikijs/core': ^3.0.0
  '@shikijs/engine-javascript': ^3.14.0
  '@shikijs/langs': ^3.14.0
  '@shikijs/themes': ^3.14.0
  '@types/node': ^24.10.0
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@unocss/reset': ^66.5.4
  '@vitejs/plugin-react': ^5.1.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vueuse/core': ^14.0.0
  bumpp: ^10.3.1
  eslint: ^9.39.1
  eslint-plugin-react-hooks: ^7.0.1
  lint-staged: ^16.2.6
  pnpm: ^10.20.0
  react: ^19.2.0
  react-dom: ^19.2.0
  shiki: ^3.14.0
  simple-git-hooks: ^2.13.1
  taze: ^19.9.0
  tsx: ^4.20.6
  typescript: ~5.9.3
  unbuild: ^3.6.1
  unocss: ^66.5.4
  vite: ^7.1.12
  vite-plugin-solid: ^2.11.10
  vitest: ^4.0.7
  vue: ^3.5.22
  vue-tsc: ^3.1.3
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - simple-git-hooks
